### PR TITLE
Split `hh` into library and front end to ease the development of copatible utilities

### PR DESCRIPTION
**Pull request by luke-clifton**
**Don't merge yet**

I need to build a bunch of utilities that I would like to be compatible with the `hh` ecosystem (similar user experience, reuse config, similar error messages etc). To such an end, I would like to split out some of `hh`'s user facing utility functions (e.g. argument parsing, config parsing, autocomplete) into a library which is distinct from `hadoop-rpc` (which should just remain a fairly raw interface to the hadoop rpc service).

I have done this by making `hadoop-tools` create both an executable, and a library.

@jystic Would you be open to such a change?

This still needs a lot of cleaning up.

### CODE REVIEW

**Comment by jystic** [comment]
I like this idea, keep going for it :+1:

**Comment by luke-clifton** [comment]
Does anyone care about 7.8 still?

**Comment by jystic** [comment]
Happy to drop support if you like

**Comment by luke-clifton** [comment]
I'll make it work, just installing 7.8.4 and building libraries now.

**Comment by jystic** [comment]
> I'll make it work, just installing 7.8.4 and building libraries now.

I honestly don't mind dropping support, the code would be a lot cleaner with AMP.

The docker image is for 7.10.1 so that will be fine.

**Comment by luke-clifton** [comment]
Ok. I'll drop 7.8.4 as part of this.

**Comment by luke-clifton** [comment]
Ok. I'm relatively happy with it. Tests pass and the CentOS build works.

- I ditched the lock files (they aren't being used by the CentOS build anyway).
- I bumped `clock` bounds to include the fix I mentioned in https://github.com/jystic/hadoop-tools/issues/27
- I abstracted some file/directory argument parsing, but didn't change anything
- Moved all useful functions into `lib/Hadoop/Tools/`

**Comment by jystic** [comment]
Looking good, mind if I just nitpick one thing? (file locations)

Would prefer to have the library stuff in `src/` and then move `src/Main.hs` to `main/hh.hs`. This matches the convention I've settled on for all my projects.

**Comment by jystic** [comment]
Awesome stuff, merging away :100:

**Pull request merged**
